organization_name: Foo Bar Baz Industries, LLC Inc. A division of Holdings Co.

environment: development

log_directory: log

log_level: Logger::DEBUG

ssl_enabled: false

# Use this example if you are using LDAP as your authentication source
# cas_adapter:
#   adapter: ldap
#   host: localhost
#   port: 389
#   prefix: cn=
#   base: dc=example, dc=com

# Uncomment these to enable authentication callbacks
# callbacks:
#  on_authentication_success: http://example.com/authentication/success
#  on_authentication_failed: http://example.com/authentication/failed
